# Generated by Django 4.2.3 on 2023-08-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_classdetails_array_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdetails',
            old_name='name',
            new_name='classCode',
        ),
        migrations.RemoveField(
            model_name='classdetails',
            name='array_name',
        ),
        migrations.AddField(
            model_name='classdetails',
            name='classEnd',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='classRoom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='classStart',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='classSubject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='teacherInit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
