# Generated by Django 4.2.3 on 2023-08-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_rename_name_classdetails_classcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.batch'),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.dept'),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.section'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(default='50', max_length=200),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='classCode',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='classEnd',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='classRoom',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='classStart',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='classSubject',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.day'),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='teacherInit',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='dept',
            name='name',
            field=models.CharField(default='CSE', max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='A', max_length=200),
        ),
    ]
