# Generated by Django 4.2.3 on 2023-08-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_classdetails_batch_classdetails_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetails',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.batch'),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.dept'),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.section'),
        ),
    ]
