# Generated by Django 4.2.3 on 2023-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_batch_id_alter_day_id_alter_dept_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetails',
            name='day',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
