# Generated by Django 4.2.3 on 2023-08-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_alter_classdetails_day_delete_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='info.dept'),
        ),
    ]
