# Generated by Django 4.2.4 on 2023-09-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_rename_day_name_busday_day_remove_busday_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='busschedule',
            name='route_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.route'),
        ),
    ]
