# Generated by Django 4.2.5 on 2023-09-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0030_route_busschedule_route_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
