# Generated by Django 4.2.5 on 2023-10-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_route_busschedule_route_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetails',
            name='classEnd',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='classStart',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
