# Generated by Django 4.2.5 on 2023-09-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_route_busschedule_route_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busday',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
