# Generated by Django 4.2.5 on 2023-09-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_route_busschedule_route_type'),
        ('info', '0032_alter_assign_unique_together_remove_assign_class_id_and_more'),
    ]

    operations = [
    ]
