# Generated by Django 4.2.5 on 2023-10-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_alter_busschedule_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.busday'),
        ),
    ]
