# Generated by Django 4.2.5 on 2023-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_alter_busschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='time_of_day',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
